## November 2023: Time of Hire
I accepted the position loosely titled Digital Marketing Manager in November while working fulltime as an English teacher in Clear Lake, WI. At this time, I was transitioning out of the education field to enter the field of technical communication. 

*Qualifications at the time of hire included:* 

* Writer of the first two Phipps Biannual Community Report magazines 
* Chair of the Younger Demographic Committee, which was tasked with advising the Phipps on methods to attract an audience younger than 50 to the Phipps. 
* Familiarity with all Phipps councils due to experience in all facets of the Phipps:
    + Children’s Theater: I grew up under John Potter’s tutelage in the senior shows
    + Drama Council: I performed in several Drama Council shows such as The Producers
    + Dance Council: I performed for several Phipps Dance Theater shows
    + Visual Arts Council: I worked for Anastasia Shartin as the Summer Arts Camp Coordinator for several summers
    + Music Council: I have worked with Tom Dahle in several Phipps musicals and interviewed Carol Dahle for one of the community report magazines
    + Volunteer Council: I have volunteered for the Phipps and interviewed Volunteer Council members such as Dawn Lewandowski and Nancy Burman for community report magazines
