## Current Responsibilities

My current responsibilities include elements of design, marketing, communications, and technical management. You can review my work anywhere on the Phipps social media sites, on ThePhipps.org, and, if you’re on the lists for emails, marquees, and the community reports, even in your own emails inboxes or on your coffee tables! 

* Emails
    +	Biweekly What’s Abuzz community newsletter
    +	Donation drive emails
    +	Targeted performance emails
    +	Classes announcement and marketing emails
    +	Any other emails requested by administration
*	Social media
    +	Design of social media graphics
    +	Creation and scheduling of social media posts
    +	Management of social media messaging, for community questions and comments
*	Website management
    +	Creation of new pages
    +	Administration of redirects
    +	Manipulation of existing photos and artwork to fit different items
    +	Troubleshooting of broken of poor-performing aspects of the website
    +	Writing new content for pages
*	Graphic design
    +	Creation of static and animated social media graphics
    +	Creation of artwork for all concerts and special events
    +	Manipulation of theater artwork from outside designer 
