## Full-Time
**Title:** 			Technical and Marketing Communications Manager

**Compensation:** 	$80,000/year full-time salary with minimum 14 days PTO, 40 hours/week, to grow at a rate of 3% annually, dependent on performance

**Increased Duties:**	Working full-time at the Phipps, I would be able to assume the following responsibilities, which would greatly improve the efficiency of workflow at the Phipps: 

* Design of the marquees, community reports, and other brochures
* Design of logos, graphics, and artwork for plays, musicals, special events, and dance theater performances that can be fully manipulated and modified throughout the year
* Creation of physical marketing such as press releases
* Development of any new marketing, technical, or communications projects that are proposed
* Regular acquisition of photos and materials from Phipps events due to more frequent visits to the building. 
* Exploration of new social media endeavors, namely YouTube Shorts (a popular American alternative to TikTok)
